### PR TITLE
Update to Python 3.7

### PR DESCRIPTION
**Pull request by wbinek**
Updates dependencies to:
 - Python 3.7
 - Boost 1.69
 - wxWidgets 3.1.2

### CODE REVIEW

**Comment by nicolas-f** [comment]
Thanks for the PR. It may help for Windows 10 compatibility.

**Comment by wbinek** [comment]
I've just noticed that there may be a regression with translations. When there are no translation files and I-SIMPA loads in English, python works fine, but when it loads translations there are some encoding errors. I am not sure how to fix it...

**Comment by wbinek** [comment]
I have found that errors were caused by translations in export_project_class() function. I have deleted the calls for translations but probably a better fix can be found.

**Comment by Picaut** [comment]
Thank you very much for you contribution!

**Comment by wbinek** [comment]
I have added another fix for encoding problems. This fixes non ascii characters displayed incorrectly in GUI. 

I have also noticed that after the updates there is a problem with setting translation language to other than used on the system. Some labels remain translated to system language.

**Comment by wbinek** [comment]
Sorry, the last one allows for changing from Polish to English but when I try to set French there is still an issue, I will try to find some better solution.

**Comment by wbinek** [comment]
There seems to be an error with wxWidgets 3.12.2 (https://trac.wxwidgets.org/ticket/18297). I will revert the last commit and wait for the release.

**Comment by Picaut** [comment]
Thank you very much. We appreciate your contribution to I-Simpa.

**Comment by nicolas-f** [comment]
@wbinek Thanks for the help, I merged your commits with some changes in other PR.

**Pull request merged**
